### ISSUE TITLE
Экранирование кавычек

### ISSUE THREAD

**Issue by Zergud** [Kokoreff081/IntiledTest#1]
1. В выходном json все кавычки экранированы
2. первая и последняя кавычки лишние

**что есть:**

`"[{\"type\":\"folder\",\"name\":\"Adobe.Master.Collection.CC.2017\",\"createTime\":\"2019-10-10T15:35:55.7034054+03:00\",\"modifyTime\":\"2019-10-10T15:38:53.3240471+03:00\"},{\"type\":\"folder\",\"name\":\"Autodesk - Maya 2017 Win x64\",\"createTime\":\"2019-10-10T15:35:43.3935333+03:00\",\"modifyTime\":\"2019-10-10T15:35:55.6565305+03:00\"},{\"type\":\"folder\",\"name\":\"Autodesk_3ds_Max_2017\",\"createTime\":\"2019-10-10T15:45:11.3303575+03:00\",\"modifyTime\":\"2019-10-10T15:46:13.7460906+03:00\"},{\"type\":\"folder\",\"name\":\"Virtual Audio Cable\",\"createTime\":\"2020-05-14T16:39:00.7883761+03:00\",\"modifyTime\":\"2020-02-01T19:58:05.8189378+03:00\"},{\"type\":\"file\",\"name\":\"Adobe Audition CC.exe\",\"createTime\":\"2020-05-14T16:38:17.4065502+03:00\",\"modifyTime\":\"2014-02-12T09:01:33+04:00\"},{\"type\":\"file\",\"name\":\"OBS-Studio-25.0.4-Full-Installer-x64.exe\",\"createTime\":\"2020-05-14T16:34:30.5381444+03:00\",\"modifyTime\":\"2020-04-24T12:37:25.3715175+03:00\"},{\"type\":\"file\",\"name\":\"Virtual Audio Cable.rar\",\"createTime\":\"2020-05-14T16:34:25.1847371+03:00\",\"modifyTime\":\"2020-04-24T14:47:57.5888526+03:00\"}]"`

**надо** 

```json
[
{
    "type": "folder",
    "name": "Adobe.Master.Collection.CC.2017",
    "createTime": "2019-10-10T15:35:55.7034054+03:00",
    "modifyTime": "2019-10-10T15:38:53.3240471+03:00"
}, {
    "type": "folder",
    "name": "Autodesk - Maya 2017 Win x64",
    "createTime": "2019-10-10T15:35:43.3935333+03:00",
    "modifyTime": "2019-10-10T15:35:55.6565305+03:00"
}, {
    "type": "folder",
    "name": "Autodesk_3ds_Max_2017",
    "createTime": "2019-10-10T15:45:11.3303575+03:00",
    "modifyTime": "2019-10-10T15:46:13.7460906+03:00"
}, {
    "type": "folder",
    "name": "Virtual Audio Cable",
    "createTime": "2020-05-14T16:39:00.7883761+03:00",
    "modifyTime": "2020-02-01T19:58:05.8189378+03:00"
}, {
    "type": "file",
    "name": "Adobe Audition CC.exe",
    "createTime": "2020-05-14T16:38:17.4065502+03:00",
    "modifyTime": "2014-02-12T09:01:33+04:00"
}, {
    "type": "file",
    "name": "OBS-Studio-25.0.4-Full-Installer-x64.exe",
    "createTime": "2020-05-14T16:34:30.5381444+03:00",
    "modifyTime": "2020-04-24T12:37:25.3715175+03:00"
}, {
    "type": "file",
    "name": "Virtual Audio Cable.rar",
    "createTime": "2020-05-14T16:34:25.1847371+03:00",
    "modifyTime": "2020-04-24T14:47:57.5888526+03:00"
}
]
```

**Comment by Kokoreff081** [comment]
Лишняя трансформация в json была. Исправлено.
